### ISSUE TITLE
Where to find this own driver thats referenced in the sources?

### ISSUE THREAD

**Issue by DavidXanatos** [hfiref0x/WinObjEx64#15]
Where to find this own driver that is referenced in the sources?
Would be nice to not have to boot the system in debug mode.

**Comment by hfiref0x** [comment]
Write your own?

**Comment by DavidXanatos** [comment]
but if you already did that why do int something that was already done? ;)

**Comment by hfiref0x** [comment]
I won't share it neither compiled or as source because a) it is signed with my company EV certificate b) it used in some different non public project too. 

However in 1.8.5 version I added support of some third party driver - called EnTechIo. This driver is used by multipe hardware vendor tools to read/write physical memory. So basically you can grab a copy of this driver, put in into project "drvstore" folder as ene64drv.sys, select "ReleaseWinIoDriver" configuration in WinObjEx64 project properties, compile it and you will have what you ask. Example of supported driver - https://www.virustotal.com/gui/file/06bda5a1594f7121acd2efe38ccb617fbc078bb9a70b665a5f5efd70e3013f50/details

**Comment by DavidXanatos** [comment]
ok I see,
where could I download that EnTechIo driver?

**Comment by hfiref0x** [comment]
It is a part of TOUGHRAM RGB software version 1.0.3
