### ISSUE TITLE
Use CMake for building

### ISSUE THREAD

**Issue by KOLANICH** [hfiref0x/WinObjEx64#31]
**Describe the feature**
Currently in order to build this one needs Visual Studio. Visual Studio is a non-free toolchain with telemetry. It'd be preferred to build it using Clang + MinGW-w64 stdlib.

In ordert o have cross-toolchain building it is preferred to set building with CMake. I have [a set of toolchain files](https://github.com/KOLANICH-libs/WindowsTargetToolchainFiles.cmake) that can be helpful for cross-building from Debian machines.

**Comment by hfiref0x** [comment]
Hello,

you can build it with free version of Visual Studio, Community Edition iirc (non-free problem solved) under VM environment isolated from internet (telemetry solved). This is Windows internals tool full of Microsoft VC specific usage, nonstandard RTL/headers usage, that is painfully to port on anything else because... it never was intented to be build by anything else except MSVC. However you are free to fork and do whatever you want, if you succees with your proposal and result won't break anything in current state of things then you also free to do a PR.

**Comment by KOLANICH** [comment]
>non-free problem solved

free as in `freedom`, not as in `free beer`

>under VM environment isolated from internet (telemetry solved).

1. doesn't it need Internet to be installed
2. MS toolchains are too heavyweight(*) to install them into VMs. Also they require new Windows OSes, which are also too heavy(*) for VMs (of Windows OSes I usually use only Win XP and ReactOS within VMs). Though just pulling the cable should do the job, if those toolchains work in Wine.

(*) for the PC I work on

>This is Windows internals tool full of Microsoft VC specific usage, nonstandard RTL/headers usage, that is painfully to port on anything else because... it never was intented to be build by anything else except MSVC.

Yeah, non-standard headers are pain. Some time ago (~5 years) I tried to build a driver (https://github.com/basil00/Divert) using only free SDKs and have failed (though some drivers can be built using them, they are just incomplete). Then I tried to combine WDK to to free SDKs and DDKs without success.

But I also has another experience. But it is not driver-related. When I was trying to build a TTS module for Windows using the official Speech SDK (designed to be used with Visual Studio) + clang + MinGW, it turned out a few minor automatically applicable patches were enough to make that work.

>However you are free to fork and do whatever you want, if you succeed with your proposal and result won't break anything in current state of things then you also free to do a PR.

Thanks for the info :)
