### ISSUE TITLE
How is this related to Sysinternals WinObj?

### ISSUE THREAD

**Issue by Neme12** [hfiref0x/WinObjEx64#33]
It looks like the same app to me. Did Sysinternals copy this app originally? Or is this a copy of the Sysinternals app?

**Comment by lighth7015** [comment]
It's heavily inspired by, but isn't the SAME app.

**Comment by hfiref0x** [comment]
It is unrelated. Originally this was an extended version of WinObj called WinObjEx and created by Four-F in 2003 year because SysInternals WinObj was (and is up to current date) a feature restricted trash. WinObjEx was close source and wasn't updated since 2005. This one was created on top of it features specially for x64.
